-- Roblox is Unbreakable script by morikyt (discord)
-- DISCORD SERVER https://discord.gg/xsjEY7Xw7e
-- Last Updated (February 9, 2025)

--local syn = getgenv().syn
--getgenv().syn = false

getgenv().TEXT = {}

getgenv().TEXT.en = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="by morik_yt",
    tab_home="Home",tab_teleports="Teleports",tab_farm="Farm",tab_skin="Skin Farm",tab_sell="Auto Sell",tab_mob="Mob Farm",tab_outfit="Outfit",tab_sbr="SBR",
    sec_language="Language",sec_info="Information",sec_movement="Movement",sec_misc="Misc",sec_app="App",sec_chest="Chest Farm",sec_meteorite="Meteorite Farm",
    sec_skin_sel="Skin Selection",sec_farm_settings="Farm Settings",sec_farm_control="Farm Control",sec_auto_buy="Auto Buy",
    sec_target="Target Selection",sec_move_settings="Movement Settings",sec_attack="Attack Settings",sec_farm="Farm",
    sec_player_outfit="Player & Outfit",sec_pieces="Piece Selection",sec_actions="Actions",
    lang_label="Interface Language",lang_changed="Language saved. Re-execute the script to apply.",
    welcome_title="Welcome",welcome_text="Welcome to Roblox is Unbreakable — a script created by morik_yt. If you run into any issues, join my Discord server. You can also unlock the Premium version for just $1 to get extra features.",
    join_discord="Join Discord",stand_up="Stand Up",speed_value="Speed Value",speed_hack="Speed Hack",jump_value="Jump Value",jump_hack="Jump Hack",
    heal="Heal ($50)",auto_stand="Auto Stand Summon",show_roles="Show Roles Above Players",staff_alert="Staff Alert",destroy_gui="Destroy GUI",staff_online="Staff Online",
    players="Players",npc_friendly="NPCs Friendly",npc_hostile="NPCs Hostile",search_all="Search (Players / NPCs)",search_ph="Type a name...",
    teleport="Teleport",player_not_found="Player not found or has no character.",dim_tears="Dimensional Tears",chests="Chests",
    ground_items="Items on the Ground",chest_types="Chest Types",chest_wait="Chest Wait (s)",chest_farm="Chest Farm",
    meteorite_wait="Meteorite Wait (s)",meteorite_farm="Meteorite Farm",
    skin_info_title="Info",skin_info_text="Supports Arrow, Pure Arrow, Requiem (GE to GER), Saint's Corpse parts, and Green Baby (WS to C-Moon). Auto picks the method for selected skins. StandStorage slot support included. Optional Skin Pity threshold.",
    skin_selected="Selected Skins",skin_status="Farm Status",skin_pity="Skin Pity",none="None",idle="Idle",pity_ready=" (ready)",pity_building=" (building)",
    pity_threshold_label=" | Threshold: %s%%",select_skins="Select Skins",farm_method="Farm Method",search_skin="Search Skin",search_skin_ph="Skin name",
    select_all_skins="Select All Skins",clear_skins="Clear Skin Selection",use_storage="Use StandStorage Free Slots",use_pity="Use Skin Pity Threshold",pity_threshold="Pity Threshold (%%)",
    skin_auto_farm="Skin Auto Farm",auto_buy_arrows="Auto Buy Arrows ($15k ea)",auto_buy_req="Auto Buy Requiem Arrows ($200k ea)",
    method_auto="Auto",method_arrow="Arrow",method_pure="Pure Arrow",method_requiem="Requiem (GE to GER)",method_corpse="Corpse Parts",method_green="Green Baby (WS to C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Information",sell_info_text="Selected items will be auto-sold for cash. Max cash cap: 250,000.",
    sell_selected="Selected Items",select_items="Select Items",search_items="Search Items",search_items_ph="Item name",select_all_items="Select All Items",clear_items="Clear Item Selection",auto_sell="Auto Sell",
    target_players="Target Players",target_npcs="Target NPCs (Hostile)",search="Search",search_farm_ph="Player or NPC name...",
    fly_speed="Fly Speed",height_offset="Height Offset (min 2)",stop_dist="Stop Distance",max_range="Max Detection Range",atk_delay="Attack Delay (s)",combo_count="Combo Count",
    npcs_farm="NPCs Farm",players_farm="Players Farm",stop_farm="Stop Farm",farm_stopped="Farm stopped.",
    outfit_player="Player",outfit_set="Outfit Set",head_piece="Head Piece",upper_piece="Upper Piece",lower_piece="Lower Piece",misc_piece="Misc Piece",none_opt="(none)",
    apply_pieces="Apply Selected Pieces",wear_full="Wear Full Set",clear_outfit="Clear Script Outfit",outfit="Outfit",char_not_found="Character not found.",
    outfit_applied="Outfit applied!",select_set_first="Select a set first.",set_pick_pieces="Set: %s — pick pieces below.",
    set_selected="Set selected: %s\nHead: %s | Upper: %s | Lower: %s | Misc: %s",full_set_applied="Full set applied: %s (%s pieces).",cleared_pieces="Cleared %s script-applied piece(s).",
    tp_finish="Teleport to Finish Line",anti_danger="Anti-Danger Zone",inf_stamina="Infinite Stamina for Horse (Requires corpse part)",corpse_esp="Saint's Corpse Parts ESP",auto_stage="Auto Stage + Barrier Bypass",
    skin_farm="Skin Farm",notify_auto_mixed="Auto mode: mixed types. Farming: %s",notify_not_enough="Not enough %s. Stopping.",notify_got_skin="Got: %s",notify_got_skin_stand="Got: %s (%s)",
    notify_no_corpse_skins="No corpse-stand skins selected.",notify_missing_corpse="Missing %s. Stopping.",notify_no_req="No Requiem Arrows. Stopping.",notify_no_green="No Green Baby item. Stopping.",
    notify_select_skin="Select at least one skin.",notify_remove_stand="You have a stand/skin equipped (%s). Remove it first!",notify_in_combat="You are in combat.",notify_target_skin="Target skin obtained: %s",
    status_wait_combat="Waiting — in combat",status_wait_stun="Waiting — stunned / performing move",status_storing="Storing stand to StandStorage slot...",status_removing="Removing stand...",
    status_rolling="Rolling %s for %s...",status_using="Using %s...",status_using_for="Using %s for %s...",status_pity_low="Pity too low (%.1f%% / %.1f%%) — rolling Arrow...",
    status_building_pity="Building pity: %.1f%% / %.1f%% (Arrow only)",status_phase1_ge="Phase 1/2 — rolling Arrow for Gold Experience...",status_phase2_req="Phase 2/2 — using Requiem Arrow on Gold Experience...",
    status_phase1_ws="Phase 1/2 — rolling Arrow for Whitesnake...",status_phase2_gb="Phase 2/2 — merging Green Baby into Whitesnake...",status_remove_first="Stopped — remove your stand/skin first.",
    status_starting="Starting — method: %s",status_done="Done — got target skin: %s",status_stopped="Stopped.",
}

getgenv().TEXT.ru = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="от morik_yt",
    tab_home="Главная",tab_teleports="Телепорты",tab_farm="Фарм",tab_skin="Фарм скинов",tab_sell="Авто продажа",tab_mob="Фарм мобов",tab_outfit="Одежда",tab_sbr="SBR",
    sec_language="Язык",sec_info="Информация",sec_movement="Движение",sec_misc="Разное",sec_app="Приложение",sec_chest="Фарм сундуков",sec_meteorite="Фарм метеоритов",
    sec_skin_sel="Выбор скинов",sec_farm_settings="Настройки фарма",sec_farm_control="Управление",sec_auto_buy="Авто покупка",
    sec_target="Выбор цели",sec_move_settings="Настройки движения",sec_attack="Настройки атаки",sec_farm="Фарм",
    sec_player_outfit="Игрок и одежда",sec_pieces="Выбор частей",sec_actions="Действия",
    lang_label="Язык интерфейса",lang_changed="Язык сохранён. Перезапусти скрипт для применения.",
    welcome_title="Добро пожаловать",welcome_text="Добро пожаловать в Roblox is Unbreakable — скрипт от morik_yt. Если возникнут проблемы, зайди в Discord. Premium версия с доп. функциями — всего $1.",
    join_discord="Discord",stand_up="Встать",speed_value="Скорость",speed_hack="Спидхак",jump_value="Прыжок",jump_hack="Прыжок хак",
    heal="Лечение ($50)",auto_stand="Авто призыв стенда",show_roles="Роли над игроками",staff_alert="Алерт стаффа",destroy_gui="Закрыть GUI",staff_online="Стафф онлайн",
    players="Игроки",npc_friendly="NPC дружел.",npc_hostile="NPC враждеб.",search_all="Поиск (игроки / NPC)",search_ph="Введи имя...",
    teleport="Телепорт",player_not_found="Игрок не найден или без персонажа.",dim_tears="Разрывы",chests="Сундуки",
    ground_items="Предметы на земле",chest_types="Типы сундуков",chest_wait="Задержка сундука (с)",chest_farm="Фарм сундуков",
    meteorite_wait="Задержка метеорита (с)",meteorite_farm="Фарм метеоритов",
    skin_info_title="Инфо",skin_info_text="Поддержка Arrow, Pure Arrow, Requiem (GE to GER), частей трупа святого и Green Baby (WS to C-Moon). Авто выбор метода. StandStorage включён. Skin Pity порог.",
    skin_selected="Выбранные скины",skin_status="Статус фарма",skin_pity="Skin Pity",none="Нет",idle="Ожидание",pity_ready=" (готово)",pity_building=" (копим)",
    pity_threshold_label=" | Порог: %s%%",select_skins="Выбрать скины",farm_method="Метод фарма",search_skin="Поиск скина",search_skin_ph="Имя скина",
    select_all_skins="Выбрать все",clear_skins="Очистить выбор",use_storage="Использовать StandStorage",use_pity="Порог Skin Pity",pity_threshold="Порог Pity (%%)",
    skin_auto_farm="Авто фарм скинов",auto_buy_arrows="Авто покупка Arrow ($15k)",auto_buy_req="Авто покупка Requiem ($200k)",
    method_auto="Авто",method_arrow="Arrow",method_pure="Pure Arrow",method_requiem="Requiem (GE to GER)",method_corpse="Части трупа",method_green="Green Baby (WS to C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Информация",sell_info_text="Выбранные предметы продаются автоматически. Лимит: 250,000.",
    sell_selected="Выбранные предметы",select_items="Выбрать предметы",search_items="Поиск предметов",search_items_ph="Имя предмета",select_all_items="Выбрать все",clear_items="Очистить выбор",auto_sell="Авто продажа",
    target_players="Цели — игроки",target_npcs="Цели — NPC",search="Поиск",search_farm_ph="Имя игрока или NPC...",
    fly_speed="Скорость полёта",height_offset="Высота (мин. 2)",stop_dist="Дистанция остановки",max_range="Макс. дистанция",atk_delay="Задержка атаки (с)",combo_count="Комбо ударов",
    npcs_farm="Фарм NPC",players_farm="Фарм игроков",stop_farm="Стоп фарм",farm_stopped="Фарм остановлен.",
    outfit_player="Игрок",outfit_set="Набор одежды",head_piece="Голова",upper_piece="Верх",lower_piece="Низ",misc_piece="Разное",none_opt="(нет)",
    apply_pieces="Применить выбранное",wear_full="Надеть полный сет",clear_outfit="Снять одежду скрипта",outfit="Одежда",char_not_found="Персонаж не найден.",
    outfit_applied="Одежда применена!",select_set_first="Сначала выбери сет.",set_pick_pieces="Сет: %s — выбери части ниже.",
    set_selected="Сет: %s\nГолова: %s | Верх: %s | Низ: %s | Разное: %s",full_set_applied="Полный сет: %s (%s частей).",cleared_pieces="Удалено %s частей скрипта.",
    tp_finish="Телепорт к финишу",anti_danger="Анти опасная зона",inf_stamina="Беск. стамина лошади (нужна часть трупа)",corpse_esp="ESP частей трупа",auto_stage="Авто стадия + барьер",
    skin_farm="Фарм скинов",notify_auto_mixed="Авто: смешанные типы. Фарм: %s",notify_not_enough="Не хватает %s. Остановка.",notify_got_skin="Выпало: %s",notify_got_skin_stand="Выпало: %s (%s)",
    notify_no_corpse_skins="Не выбраны скины с частями трупа.",notify_missing_corpse="Нет %s. Остановка.",notify_no_req="Нет Requiem Arrow. Остановка.",notify_no_green="Нет Green Baby. Остановка.",
    notify_select_skin="Выбери хотя бы один скин.",notify_remove_stand="У тебя стоит стенд/скин (%s). Сними его!",notify_in_combat="Ты в бою.",notify_target_skin="Целевой скин получен: %s",
    status_wait_combat="Ожидание — бой",status_wait_stun="Ожидание — стан / атака",status_storing="Сохранение в StandStorage...",status_removing="Снятие стенда...",
    status_rolling="Кручу %s для %s...",status_using="Использую %s...",status_using_for="Использую %s для %s...",status_pity_low="Pity низкий (%.1f%% / %.1f%%) — кручу Arrow...",
    status_building_pity="Коплю pity: %.1f%% / %.1f%% (только Arrow)",status_phase1_ge="Фаза 1/2 — Arrow для Gold Experience...",status_phase2_req="Фаза 2/2 — Requiem Arrow на Gold Experience...",
    status_phase1_ws="Фаза 1/2 — Arrow для Whitesnake...",status_phase2_gb="Фаза 2/2 — Green Baby в Whitesnake...",status_remove_first="Стоп — сними стенд/скин.",
    status_starting="Старт — метод: %s",status_done="Готово — скин: %s",status_stopped="Остановлено.",
}

getgenv().TEXT.de = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="von morik_yt",
    tab_home="Start",tab_teleports="Teleport",tab_farm="Farm",tab_skin="Skin-Farm",tab_sell="Auto-Verkauf",tab_mob="Mob-Farm",tab_outfit="Outfit",tab_sbr="SBR",
    sec_language="Sprache",sec_info="Information",sec_movement="Bewegung",sec_misc="Sonstiges",sec_app="App",sec_chest="Truhen-Farm",sec_meteorite="Meteoriten-Farm",
    sec_skin_sel="Skin-Auswahl",sec_farm_settings="Farm-Einstellungen",sec_farm_control="Farm-Steuerung",sec_auto_buy="Auto-Kauf",
    sec_target="Zielauswahl",sec_move_settings="Bewegungseinstellungen",sec_attack="Angriffs-Einstellungen",sec_farm="Farm",
    sec_player_outfit="Spieler & Outfit",sec_pieces="Teile-Auswahl",sec_actions="Aktionen",
    lang_label="Oberflächensprache",lang_changed="Sprache gespeichert. Skript neu starten zum Anwenden.",
    welcome_title="Willkommen",welcome_text="Willkommen bei Roblox is Unbreakable — einem Skript von morik_yt. Bei Problemen tritt dem Discord bei. Premium-Version für nur $1 verfügbar.",
    join_discord="Discord beitreten",stand_up="Aufstehen",speed_value="Geschwindigkeit",speed_hack="Speed-Hack",jump_value="Sprungkraft",jump_hack="Sprung-Hack",
    heal="Heilen ($50)",auto_stand="Auto-Stand-Beschwörung",show_roles="Rollen über Spielern",staff_alert="Staff-Alarm",destroy_gui="GUI schließen",staff_online="Staff online",
    players="Spieler",npc_friendly="Freundliche NPCs",npc_hostile="Feindliche NPCs",search_all="Suche (Spieler / NPCs)",search_ph="Name eingeben...",
    teleport="Teleport",player_not_found="Spieler nicht gefunden oder kein Charakter.",dim_tears="Dimensionsrisse",chests="Truhen",
    ground_items="Gegenstände am Boden",chest_types="Truhentypen",chest_wait="Truhen-Wartezeit (s)",chest_farm="Truhen-Farm",
    meteorite_wait="Meteoriten-Wartezeit (s)",meteorite_farm="Meteoriten-Farm",
    skin_info_title="Info",skin_info_text="Unterstützt Arrow, Pure Arrow, Requiem (GE zu GER), Heilige Leichenteile und Green Baby (WS zu C-Moon). Automatische Methodenwahl. StandStorage enthalten.",
    skin_selected="Ausgewählte Skins",skin_status="Farm-Status",skin_pity="Skin Pity",none="Keiner",idle="Inaktiv",pity_ready=" (bereit)",pity_building=" (aufbauend)",
    pity_threshold_label=" | Schwelle: %s%%",select_skins="Skins auswählen",farm_method="Farm-Methode",search_skin="Skin suchen",search_skin_ph="Skin-Name",
    select_all_skins="Alle Skins wählen",clear_skins="Auswahl leeren",use_storage="StandStorage-Slots nutzen",use_pity="Skin-Pity-Schwelle nutzen",pity_threshold="Pity-Schwelle (%%)",
    skin_auto_farm="Skin-Auto-Farm",auto_buy_arrows="Auto-Kauf Pfeile ($15k)",auto_buy_req="Auto-Kauf Requiem-Pfeile ($200k)",
    method_auto="Auto",method_arrow="Pfeil",method_pure="Reiner Pfeil",method_requiem="Requiem (GE zu GER)",method_corpse="Leichenteile",method_green="Green Baby (WS zu C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Information",sell_info_text="Ausgewählte Gegenstände werden automatisch verkauft. Max. 250.000.",
    sell_selected="Ausgewählte Gegenstände",select_items="Gegenstände auswählen",search_items="Gegenstände suchen",search_items_ph="Gegenstandsname",select_all_items="Alle auswählen",clear_items="Auswahl leeren",auto_sell="Auto-Verkauf",
    target_players="Ziel — Spieler",target_npcs="Ziel — NPCs (Feindlich)",search="Suche",search_farm_ph="Spieler- oder NPC-Name...",
    fly_speed="Fluggeschwindigkeit",height_offset="Höhenversatz (min. 2)",stop_dist="Stoppdistanz",max_range="Max. Erkennungsreichweite",atk_delay="Angriffsverzögerung (s)",combo_count="Kombo-Anzahl",
    npcs_farm="NPCs farmen",players_farm="Spieler farmen",stop_farm="Farm stoppen",farm_stopped="Farm gestoppt.",
    outfit_player="Spieler",outfit_set="Outfit-Set",head_piece="Kopfteil",upper_piece="Oberteil",lower_piece="Unterteil",misc_piece="Sonstiges",none_opt="(keins)",
    apply_pieces="Auswahl anwenden",wear_full="Komplettes Set anziehen",clear_outfit="Skript-Outfit entfernen",outfit="Outfit",char_not_found="Charakter nicht gefunden.",
    outfit_applied="Outfit angewendet!",select_set_first="Zuerst ein Set auswählen.",set_pick_pieces="Set: %s — Teile unten wählen.",
    set_selected="Set: %s\nKopf: %s | Oben: %s | Unten: %s | Sonstiges: %s",full_set_applied="Komplettes Set: %s (%s Teile).",cleared_pieces="%s Skript-Teil(e) entfernt.",
    tp_finish="Zur Ziellinie teleportieren",anti_danger="Anti-Gefahrenzone",inf_stamina="Unendl. Ausdauer (Leichenteile nötig)",corpse_esp="Heilige Leichenteile ESP",auto_stage="Auto-Phase + Barrieren-Bypass",
    skin_farm="Skin-Farm",notify_auto_mixed="Auto: gemischte Typen. Farme: %s",notify_not_enough="Nicht genug %s. Stoppe.",notify_got_skin="Erhalten: %s",notify_got_skin_stand="Erhalten: %s (%s)",
    notify_no_corpse_skins="Keine Leichen-Skins ausgewählt.",notify_missing_corpse="%s fehlt. Stoppe.",notify_no_req="Kein Requiem-Pfeil. Stoppe.",notify_no_green="Kein Green Baby. Stoppe.",
    notify_select_skin="Mindestens einen Skin auswählen.",notify_remove_stand="Stand/Skin ausgerüstet (%s). Zuerst entfernen!",notify_in_combat="Du bist im Kampf.",notify_target_skin="Ziel-Skin erhalten: %s",
    status_wait_combat="Warten — im Kampf",status_wait_stun="Warten — betäubt / Aktion",status_storing="In StandStorage-Slot speichern...",status_removing="Stand entfernen...",
    status_rolling="%s für %s würfeln...",status_using="%s benutzen...",status_using_for="%s für %s benutzen...",status_pity_low="Pity zu niedrig (%.1f%% / %.1f%%) — Pfeil benutzen...",
    status_building_pity="Pity aufbauen: %.1f%% / %.1f%% (nur Pfeil)",status_phase1_ge="Phase 1/2 — Pfeil für Gold Experience...",status_phase2_req="Phase 2/2 — Requiem-Pfeil auf Gold Experience...",
    status_phase1_ws="Phase 1/2 — Pfeil für Whitesnake...",status_phase2_gb="Phase 2/2 — Green Baby mit Whitesnake verbinden...",status_remove_first="Gestoppt — Stand/Skin zuerst entfernen.",
    status_starting="Start — Methode: %s",status_done="Fertig — Skin: %s",status_stopped="Gestoppt.",
}

getgenv().TEXT.fr = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="par morik_yt",
    tab_home="Accueil",tab_teleports="Téléports",tab_farm="Farm",tab_skin="Farm de skins",tab_sell="Vente auto",tab_mob="Farm de mobs",tab_outfit="Tenue",tab_sbr="SBR",
    sec_language="Langue",sec_info="Information",sec_movement="Déplacement",sec_misc="Divers",sec_app="Application",sec_chest="Farm coffres",sec_meteorite="Farm météorites",
    sec_skin_sel="Sélection de skins",sec_farm_settings="Paramètres du farm",sec_farm_control="Contrôle du farm",sec_auto_buy="Achat automatique",
    sec_target="Sélection de cible",sec_move_settings="Paramètres de déplacement",sec_attack="Paramètres d'attaque",sec_farm="Farm",
    sec_player_outfit="Joueur & Tenue",sec_pieces="Sélection de pièces",sec_actions="Actions",
    lang_label="Langue de l'interface",lang_changed="Langue sauvegardée. Relancez le script pour appliquer.",
    welcome_title="Bienvenue",welcome_text="Bienvenue dans Roblox is Unbreakable — un script créé par morik_yt. En cas de problème, rejoignez le Discord. Version Premium à seulement $1.",
    join_discord="Rejoindre Discord",stand_up="Se lever",speed_value="Vitesse",speed_hack="Speed Hack",jump_value="Saut",jump_hack="Jump Hack",
    heal="Soigner ($50)",auto_stand="Invocation auto du Stand",show_roles="Afficher les rôles",staff_alert="Alerte staff",destroy_gui="Fermer le GUI",staff_online="Staff en ligne",
    players="Joueurs",npc_friendly="PNJ amicaux",npc_hostile="PNJ hostiles",search_all="Recherche (Joueurs / PNJ)",search_ph="Entrer un nom...",
    teleport="Téléport",player_not_found="Joueur introuvable ou sans personnage.",dim_tears="Déchirures dimensionnelles",chests="Coffres",
    ground_items="Objets au sol",chest_types="Types de coffres",chest_wait="Attente coffre (s)",chest_farm="Farm coffres",
    meteorite_wait="Attente météorite (s)",meteorite_farm="Farm météorites",
    skin_info_title="Info",skin_info_text="Supporte Arrow, Pure Arrow, Requiem (GE vers GER), parties du corps du Saint et Green Baby (WS vers C-Moon). Sélection automatique. StandStorage inclus.",
    skin_selected="Skins sélectionnés",skin_status="Statut du farm",skin_pity="Skin Pity",none="Aucun",idle="Inactif",pity_ready=" (prêt)",pity_building=" (accumulation)",
    pity_threshold_label=" | Seuil : %s%%",select_skins="Sélectionner des skins",farm_method="Méthode de farm",search_skin="Rechercher un skin",search_skin_ph="Nom du skin",
    select_all_skins="Tout sélectionner",clear_skins="Effacer la sélection",use_storage="Utiliser les slots StandStorage",use_pity="Utiliser le seuil Skin Pity",pity_threshold="Seuil Pity (%%)",
    skin_auto_farm="Auto-farm de skins",auto_buy_arrows="Achat auto Flèches ($15k)",auto_buy_req="Achat auto Flèches Requiem ($200k)",
    method_auto="Auto",method_arrow="Flèche",method_pure="Flèche pure",method_requiem="Requiem (GE vers GER)",method_corpse="Parties du corps",method_green="Green Baby (WS vers C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Information",sell_info_text="Les objets sélectionnés seront vendus automatiquement. Plafond : 250 000.",
    sell_selected="Objets sélectionnés",select_items="Sélectionner des objets",search_items="Rechercher des objets",search_items_ph="Nom de l'objet",select_all_items="Tout sélectionner",clear_items="Effacer la sélection",auto_sell="Vente automatique",
    target_players="Cibles — Joueurs",target_npcs="Cibles — PNJ (Hostiles)",search="Recherche",search_farm_ph="Nom du joueur ou PNJ...",
    fly_speed="Vitesse de vol",height_offset="Décalage hauteur (min 2)",stop_dist="Distance d'arrêt",max_range="Portée max de détection",atk_delay="Délai d'attaque (s)",combo_count="Nombre de combos",
    npcs_farm="Farm PNJ",players_farm="Farm joueurs",stop_farm="Arrêter le farm",farm_stopped="Farm arrêté.",
    outfit_player="Joueur",outfit_set="Set de tenue",head_piece="Tête",upper_piece="Haut",lower_piece="Bas",misc_piece="Divers",none_opt="(aucun)",
    apply_pieces="Appliquer la sélection",wear_full="Porter le set complet",clear_outfit="Retirer la tenue du script",outfit="Tenue",char_not_found="Personnage introuvable.",
    outfit_applied="Tenue appliquée !",select_set_first="Sélectionnez d'abord un set.",set_pick_pieces="Set : %s — choisissez les pièces.",
    set_selected="Set : %s\nTête : %s | Haut : %s | Bas : %s | Divers : %s",full_set_applied="Set complet : %s (%s pièces).",cleared_pieces="%s pièce(s) du script retirée(s).",
    tp_finish="Téléport à l'arrivée",anti_danger="Anti-zone de danger",inf_stamina="Endurance infinie (partie du corps requise)",corpse_esp="ESP parties du corps",auto_stage="Phase auto + contournement barrière",
    skin_farm="Farm de skins",notify_auto_mixed="Auto : types mixtes. Farm : %s",notify_not_enough="Pas assez de %s. Arrêt.",notify_got_skin="Obtenu : %s",notify_got_skin_stand="Obtenu : %s (%s)",
    notify_no_corpse_skins="Aucun skin de cadavre sélectionné.",notify_missing_corpse="%s manquant. Arrêt.",notify_no_req="Pas de Flèche Requiem. Arrêt.",notify_no_green="Pas de Green Baby. Arrêt.",
    notify_select_skin="Sélectionnez au moins un skin.",notify_remove_stand="Stand/Skin équipé (%s). Retirez-le d'abord !",notify_in_combat="Vous êtes en combat.",notify_target_skin="Skin cible obtenu : %s",
    status_wait_combat="Attente — en combat",status_wait_stun="Attente — étourdi / action",status_storing="Stockage dans StandStorage...",status_removing="Retrait du Stand...",
    status_rolling="Lancement de %s pour %s...",status_using="Utilisation de %s...",status_using_for="Utilisation de %s pour %s...",status_pity_low="Pity trop bas (%.1f%% / %.1f%%) — Flèche en cours...",
    status_building_pity="Accumulation pity : %.1f%% / %.1f%% (Flèche seulement)",status_phase1_ge="Phase 1/2 — Flèche pour Gold Experience...",status_phase2_req="Phase 2/2 — Flèche Requiem sur Gold Experience...",
    status_phase1_ws="Phase 1/2 — Flèche pour Whitesnake...",status_phase2_gb="Phase 2/2 — Fusion Green Baby avec Whitesnake...",status_remove_first="Arrêté — retirez d'abord votre Stand/Skin.",
    status_starting="Démarrage — méthode : %s",status_done="Terminé — skin : %s",status_stopped="Arrêté.",
}

getgenv().TEXT.es = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="por morik_yt",
    tab_home="Inicio",tab_teleports="Teletransportes",tab_farm="Farmear",tab_skin="Farm de skins",tab_sell="Venta auto",tab_mob="Farm de mobs",tab_outfit="Atuendo",tab_sbr="SBR",
    sec_language="Idioma",sec_info="Información",sec_movement="Movimiento",sec_misc="Miscelánea",sec_app="Aplicación",sec_chest="Farm cofres",sec_meteorite="Farm meteoritos",
    sec_skin_sel="Selección de skins",sec_farm_settings="Configuración del farm",sec_farm_control="Control del farm",sec_auto_buy="Compra automática",
    sec_target="Selección de objetivo",sec_move_settings="Configuración de movimiento",sec_attack="Configuración de ataque",sec_farm="Farm",
    sec_player_outfit="Jugador y atuendo",sec_pieces="Selección de piezas",sec_actions="Acciones",
    lang_label="Idioma de la interfaz",lang_changed="Idioma guardado. Vuelve a ejecutar el script para aplicar.",
    welcome_title="Bienvenido",welcome_text="Bienvenido a Roblox is Unbreakable — un script creado por morik_yt. Si tienes problemas únete al Discord. Versión Premium por solo $1.",
    join_discord="Unirse al Discord",stand_up="Levantarse",speed_value="Velocidad",speed_hack="Speed Hack",jump_value="Salto",jump_hack="Jump Hack",
    heal="Curar ($50)",auto_stand="Invocación automática de Stand",show_roles="Mostrar roles",staff_alert="Alerta de staff",destroy_gui="Cerrar GUI",staff_online="Staff en línea",
    players="Jugadores",npc_friendly="NPCs amistosos",npc_hostile="NPCs hostiles",search_all="Buscar (Jugadores / NPCs)",search_ph="Escribe un nombre...",
    teleport="Teletransporte",player_not_found="Jugador no encontrado o sin personaje.",dim_tears="Grietas dimensionales",chests="Cofres",
    ground_items="Objetos en el suelo",chest_types="Tipos de cofres",chest_wait="Espera cofre (s)",chest_farm="Farm de cofres",
    meteorite_wait="Espera meteorito (s)",meteorite_farm="Farm de meteoritos",
    skin_info_title="Info",skin_info_text="Soporta Arrow, Pure Arrow, Requiem (GE a GER), partes del cuerpo del Santo y Green Baby (WS a C-Moon). Selección automática. StandStorage incluido.",
    skin_selected="Skins seleccionados",skin_status="Estado del farm",skin_pity="Skin Pity",none="Ninguno",idle="Inactivo",pity_ready=" (listo)",pity_building=" (acumulando)",
    pity_threshold_label=" | Umbral: %s%%",select_skins="Seleccionar skins",farm_method="Método de farm",search_skin="Buscar skin",search_skin_ph="Nombre del skin",
    select_all_skins="Seleccionar todo",clear_skins="Limpiar selección",use_storage="Usar slots de StandStorage",use_pity="Usar umbral de Skin Pity",pity_threshold="Umbral Pity (%%)",
    skin_auto_farm="Auto-farm de skins",auto_buy_arrows="Compra auto Flechas ($15k)",auto_buy_req="Compra auto Flechas Requiem ($200k)",
    method_auto="Auto",method_arrow="Flecha",method_pure="Flecha pura",method_requiem="Requiem (GE a GER)",method_corpse="Partes del cuerpo",method_green="Green Baby (WS a C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Información",sell_info_text="Los objetos seleccionados se venderán automáticamente. Límite: 250.000.",
    sell_selected="Objetos seleccionados",select_items="Seleccionar objetos",search_items="Buscar objetos",search_items_ph="Nombre del objeto",select_all_items="Seleccionar todo",clear_items="Limpiar selección",auto_sell="Venta automática",
    target_players="Objetivo — Jugadores",target_npcs="Objetivo — NPCs (Hostiles)",search="Buscar",search_farm_ph="Nombre del jugador o NPC...",
    fly_speed="Velocidad de vuelo",height_offset="Desplazamiento altura (min 2)",stop_dist="Distancia de parada",max_range="Rango máximo de detección",atk_delay="Retraso de ataque (s)",combo_count="Cantidad de combos",
    npcs_farm="Farmear NPCs",players_farm="Farmear jugadores",stop_farm="Detener farm",farm_stopped="Farm detenido.",
    outfit_player="Jugador",outfit_set="Set de atuendo",head_piece="Cabeza",upper_piece="Parte superior",lower_piece="Parte inferior",misc_piece="Miscelánea",none_opt="(ninguno)",
    apply_pieces="Aplicar selección",wear_full="Usar set completo",clear_outfit="Quitar atuendo del script",outfit="Atuendo",char_not_found="Personaje no encontrado.",
    outfit_applied="¡Atuendo aplicado!",select_set_first="Selecciona un set primero.",set_pick_pieces="Set: %s — elige las piezas.",
    set_selected="Set: %s\nCabeza: %s | Superior: %s | Inferior: %s | Misc: %s",full_set_applied="Set completo: %s (%s piezas).",cleared_pieces="%s pieza(s) del script eliminada(s).",
    tp_finish="Teletransporte a la meta",anti_danger="Anti-zona de peligro",inf_stamina="Resistencia infinita (requiere parte del cuerpo)",corpse_esp="ESP partes del cuerpo",auto_stage="Auto-fase + bypass de barrera",
    skin_farm="Farm de skins",notify_auto_mixed="Auto: tipos mixtos. Farmeando: %s",notify_not_enough="No hay suficiente %s. Deteniendo.",notify_got_skin="Obtenido: %s",notify_got_skin_stand="Obtenido: %s (%s)",
    notify_no_corpse_skins="No hay skins de cadáver seleccionados.",notify_missing_corpse="Falta %s. Deteniendo.",notify_no_req="Sin Flechas Requiem. Deteniendo.",notify_no_green="Sin Green Baby. Deteniendo.",
    notify_select_skin="Selecciona al menos un skin.",notify_remove_stand="Stand/Skin equipado (%s). ¡Quítalo primero!",notify_in_combat="Estás en combate.",notify_target_skin="Skin objetivo obtenido: %s",
    status_wait_combat="Esperando — en combate",status_wait_stun="Esperando — aturdido / acción",status_storing="Guardando en slot de StandStorage...",status_removing="Quitando Stand...",
    status_rolling="Usando %s para %s...",status_using="Usando %s...",status_using_for="Usando %s para %s...",status_pity_low="Pity demasiado bajo (%.1f%% / %.1f%%) — usando Flecha...",
    status_building_pity="Acumulando pity: %.1f%% / %.1f%% (solo Flecha)",status_phase1_ge="Fase 1/2 — Flecha para Gold Experience...",status_phase2_req="Fase 2/2 — Flecha Requiem en Gold Experience...",
    status_phase1_ws="Fase 1/2 — Flecha para Whitesnake...",status_phase2_gb="Fase 2/2 — Fusionando Green Baby con Whitesnake...",status_remove_first="Detenido — quita tu Stand/Skin primero.",
    status_starting="Iniciando — método: %s",status_done="Listo — skin: %s",status_stopped="Detenido.",
}

getgenv().TEXT.pt = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="por morik_yt",
    tab_home="Início",tab_teleports="Teleportes",tab_farm="Farm",tab_skin="Farm de skins",tab_sell="Venda auto",tab_mob="Farm de mobs",tab_outfit="Roupa",tab_sbr="SBR",
    sec_language="Idioma",sec_info="Informação",sec_movement="Movimento",sec_misc="Diversos",sec_app="Aplicativo",sec_chest="Farm de baús",sec_meteorite="Farm de meteoritos",
    sec_skin_sel="Seleção de skins",sec_farm_settings="Config. do farm",sec_farm_control="Controle do farm",sec_auto_buy="Compra automática",
    sec_target="Seleção de alvo",sec_move_settings="Config. de movimento",sec_attack="Config. de ataque",sec_farm="Farm",
    sec_player_outfit="Jogador e roupa",sec_pieces="Seleção de peças",sec_actions="Ações",
    lang_label="Idioma da interface",lang_changed="Idioma salvo. Reexecute o script para aplicar.",
    welcome_title="Bem-vindo",welcome_text="Bem-vindo ao Roblox is Unbreakable — um script criado por morik_yt. Se tiver problemas, entre no Discord. Versão Premium por apenas $1.",
    join_discord="Entrar no Discord",stand_up="Levantar",speed_value="Velocidade",speed_hack="Speed Hack",jump_value="Pulo",jump_hack="Jump Hack",
    heal="Curar ($50)",auto_stand="Invocação automática de Stand",show_roles="Mostrar cargos",staff_alert="Alerta de staff",destroy_gui="Fechar GUI",staff_online="Staff online",
    players="Jogadores",npc_friendly="NPCs amigáveis",npc_hostile="NPCs hostis",search_all="Pesquisar (Jogadores / NPCs)",search_ph="Digite um nome...",
    teleport="Teleporte",player_not_found="Jogador não encontrado ou sem personagem.",dim_tears="Fendas dimensionais",chests="Baús",
    ground_items="Itens no chão",chest_types="Tipos de baús",chest_wait="Espera baú (s)",chest_farm="Farm de baús",
    meteorite_wait="Espera meteorito (s)",meteorite_farm="Farm de meteoritos",
    skin_info_title="Info",skin_info_text="Suporta Arrow, Pure Arrow, Requiem (GE para GER), partes do corpo do Santo e Green Baby (WS para C-Moon). Seleção automática. StandStorage incluído.",
    skin_selected="Skins selecionados",skin_status="Status do farm",skin_pity="Skin Pity",none="Nenhum",idle="Inativo",pity_ready=" (pronto)",pity_building=" (acumulando)",
    pity_threshold_label=" | Limite: %s%%",select_skins="Selecionar skins",farm_method="Método de farm",search_skin="Pesquisar skin",search_skin_ph="Nome do skin",
    select_all_skins="Selecionar tudo",clear_skins="Limpar seleção",use_storage="Usar slots do StandStorage",use_pity="Usar limite de Skin Pity",pity_threshold="Limite Pity (%%)",
    skin_auto_farm="Auto-farm de skins",auto_buy_arrows="Compra auto Flechas ($15k)",auto_buy_req="Compra auto Flechas Requiem ($200k)",
    method_auto="Auto",method_arrow="Flecha",method_pure="Flecha pura",method_requiem="Requiem (GE para GER)",method_corpse="Partes do corpo",method_green="Green Baby (WS para C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Informação",sell_info_text="Itens selecionados serão vendidos automaticamente. Limite: 250.000.",
    sell_selected="Itens selecionados",select_items="Selecionar itens",search_items="Pesquisar itens",search_items_ph="Nome do item",select_all_items="Selecionar tudo",clear_items="Limpar seleção",auto_sell="Venda automática",
    target_players="Alvo — Jogadores",target_npcs="Alvo — NPCs (Hostis)",search="Pesquisar",search_farm_ph="Nome do jogador ou NPC...",
    fly_speed="Velocidade de voo",height_offset="Deslocamento altura (min 2)",stop_dist="Distância de parada",max_range="Alcance máx. de detecção",atk_delay="Atraso de ataque (s)",combo_count="Qtd. de combos",
    npcs_farm="Farmar NPCs",players_farm="Farmar jogadores",stop_farm="Parar farm",farm_stopped="Farm parado.",
    outfit_player="Jogador",outfit_set="Set de roupa",head_piece="Cabeça",upper_piece="Parte superior",lower_piece="Parte inferior",misc_piece="Diversos",none_opt="(nenhum)",
    apply_pieces="Aplicar seleção",wear_full="Usar set completo",clear_outfit="Remover roupa do script",outfit="Roupa",char_not_found="Personagem não encontrado.",
    outfit_applied="Roupa aplicada!",select_set_first="Selecione um set primeiro.",set_pick_pieces="Set: %s — escolha as peças.",
    set_selected="Set: %s\nCabeça: %s | Superior: %s | Inferior: %s | Misc: %s",full_set_applied="Set completo: %s (%s peças).",cleared_pieces="%s peça(s) do script removida(s).",
    tp_finish="Teleporte para a chegada",anti_danger="Anti-zona de perigo",inf_stamina="Resistência infinita (requer parte do corpo)",corpse_esp="ESP partes do corpo",auto_stage="Auto-fase + bypass de barreira",
    skin_farm="Farm de skins",notify_auto_mixed="Auto: tipos mistos. Farmando: %s",notify_not_enough="Sem %s suficiente. Parando.",notify_got_skin="Obtido: %s",notify_got_skin_stand="Obtido: %s (%s)",
    notify_no_corpse_skins="Nenhum skin de cadáver selecionado.",notify_missing_corpse="%s faltando. Parando.",notify_no_req="Sem Flechas Requiem. Parando.",notify_no_green="Sem Green Baby. Parando.",
    notify_select_skin="Selecione ao menos um skin.",notify_remove_stand="Stand/Skin equipado (%s). Remova primeiro!",notify_in_combat="Você está em combate.",notify_target_skin="Skin alvo obtido: %s",
    status_wait_combat="Aguardando — em combate",status_wait_stun="Aguardando — atordoado / ação",status_storing="Salvando no slot StandStorage...",status_removing="Removendo Stand...",
    status_rolling="Usando %s para %s...",status_using="Usando %s...",status_using_for="Usando %s para %s...",status_pity_low="Pity muito baixo (%.1f%% / %.1f%%) — usando Flecha...",
    status_building_pity="Acumulando pity: %.1f%% / %.1f%% (apenas Flecha)",status_phase1_ge="Fase 1/2 — Flecha para Gold Experience...",status_phase2_req="Fase 2/2 — Flecha Requiem em Gold Experience...",
    status_phase1_ws="Fase 1/2 — Flecha para Whitesnake...",status_phase2_gb="Fase 2/2 — Fundindo Green Baby com Whitesnake...",status_remove_first="Parado — remova seu Stand/Skin primeiro.",
    status_starting="Iniciando — método: %s",status_done="Concluído — skin: %s",status_stopped="Parado.",
}

getgenv().TEXT.tr = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="morik_yt tarafından",
    tab_home="Ana Sayfa",tab_teleports="Teleport",tab_farm="Farm",tab_skin="Skin Farm",tab_sell="Otomatik Sat",tab_mob="Mob Farm",tab_outfit="Kıyafet",tab_sbr="SBR",
    sec_language="Dil",sec_info="Bilgi",sec_movement="Hareket",sec_misc="Diğer",sec_app="Uygulama",sec_chest="Sandık Farm",sec_meteorite="Meteorit Farm",
    sec_skin_sel="Skin Seçimi",sec_farm_settings="Farm Ayarları",sec_farm_control="Farm Kontrolü",sec_auto_buy="Otomatik Satın Al",
    sec_target="Hedef Seçimi",sec_move_settings="Hareket Ayarları",sec_attack="Saldırı Ayarları",sec_farm="Farm",
    sec_player_outfit="Oyuncu ve Kıyafet",sec_pieces="Parça Seçimi",sec_actions="Eylemler",
    lang_label="Arayüz Dili",lang_changed="Dil kaydedildi. Uygulamak için scripti yeniden çalıştır.",
    welcome_title="Hoşgeldin",welcome_text="Roblox is Unbreakable'a hoşgeldin — morik_yt tarafından yapılan bir script. Sorun yaşarsan Discord'a katıl. Sadece $1 karşılığında Premium sürümü edinebilirsin.",
    join_discord="Discord'a Katıl",stand_up="Kalk",speed_value="Hız Değeri",speed_hack="Hız Hilesi",jump_value="Zıplama Değeri",jump_hack="Zıplama Hilesi",
    heal="İyileş ($50)",auto_stand="Otomatik Stand Çağır",show_roles="Oyuncuların Üstünde Rol Göster",staff_alert="Staff Uyarısı",destroy_gui="GUI'yi Kapat",staff_online="Staff Çevrimiçi",
    players="Oyuncular",npc_friendly="Dost NPC'ler",npc_hostile="Düşman NPC'ler",search_all="Ara (Oyuncular / NPC'ler)",search_ph="İsim gir...",
    teleport="Teleport",player_not_found="Oyuncu bulunamadı veya karakteri yok.",dim_tears="Boyutsal Yarıklar",chests="Sandıklar",
    ground_items="Yerdeki Eşyalar",chest_types="Sandık Türleri",chest_wait="Sandık Bekleme (s)",chest_farm="Sandık Farm",
    meteorite_wait="Meteorit Bekleme (s)",meteorite_farm="Meteorit Farm",
    skin_info_title="Bilgi",skin_info_text="Arrow, Pure Arrow, Requiem (GE'den GER'e), Aziz Ceset Parçaları ve Green Baby (WS'den C-Moon'a) desteklenir. Otomatik yöntem seçimi. StandStorage dahil.",
    skin_selected="Seçili Skinler",skin_status="Farm Durumu",skin_pity="Skin Pity",none="Yok",idle="Boşta",pity_ready=" (hazır)",pity_building=" (birikiyor)",
    pity_threshold_label=" | Eşik: %s%%",select_skins="Skin Seç",farm_method="Farm Yöntemi",search_skin="Skin Ara",search_skin_ph="Skin adı",
    select_all_skins="Tümünü Seç",clear_skins="Seçimi Temizle",use_storage="StandStorage Slotlarını Kullan",use_pity="Skin Pity Eşiğini Kullan",pity_threshold="Pity Eşiği (%%)",
    skin_auto_farm="Otomatik Skin Farm",auto_buy_arrows="Otomatik Ok Satın Al ($15k)",auto_buy_req="Otomatik Requiem Ok Satın Al ($200k)",
    method_auto="Otomatik",method_arrow="Ok",method_pure="Saf Ok",method_requiem="Requiem (GE'den GER'e)",method_corpse="Ceset Parçaları",method_green="Green Baby (WS'den C-Moon'a)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Bilgi",sell_info_text="Seçilen eşyalar otomatik satılır. Maksimum 250.000.",
    sell_selected="Seçili Eşyalar",select_items="Eşya Seç",search_items="Eşya Ara",search_items_ph="Eşya adı",select_all_items="Tümünü Seç",clear_items="Seçimi Temizle",auto_sell="Otomatik Sat",
    target_players="Hedef — Oyuncular",target_npcs="Hedef — NPC'ler (Düşman)",search="Ara",search_farm_ph="Oyuncu veya NPC adı...",
    fly_speed="Uçuş Hızı",height_offset="Yükseklik Farkı (min 2)",stop_dist="Durma Mesafesi",max_range="Maks. Algılama Menzili",atk_delay="Saldırı Gecikmesi (s)",combo_count="Kombo Sayısı",
    npcs_farm="NPC Farm",players_farm="Oyuncu Farm",stop_farm="Farmı Durdur",farm_stopped="Farm durduruldu.",
    outfit_player="Oyuncu",outfit_set="Kıyafet Seti",head_piece="Kafa Parçası",upper_piece="Üst Parça",lower_piece="Alt Parça",misc_piece="Diğer Parça",none_opt="(yok)",
    apply_pieces="Seçilenleri Uygula",wear_full="Tam Seti Giy",clear_outfit="Script Kıyafetini Kaldır",outfit="Kıyafet",char_not_found="Karakter bulunamadı.",
    outfit_applied="Kıyafet uygulandı!",select_set_first="Önce bir set seç.",set_pick_pieces="Set: %s — aşağıdan parça seç.",
    set_selected="Set: %s\nKafa: %s | Üst: %s | Alt: %s | Diğer: %s",full_set_applied="Tam set: %s (%s parça).",cleared_pieces="%s script parçası kaldırıldı.",
    tp_finish="Bitiş Çizgisine Teleport",anti_danger="Anti-Tehlike Bölgesi",inf_stamina="Sonsuz Dayanıklılık (ceset parçası gerekli)",corpse_esp="Ceset Parçaları ESP",auto_stage="Otomatik Aşama + Bariyer Bypass",
    skin_farm="Skin Farm",notify_auto_mixed="Otomatik: karışık tipler. Farming: %s",notify_not_enough="Yeterli %s yok. Durduruluyor.",notify_got_skin="Alındı: %s",notify_got_skin_stand="Alındı: %s (%s)",
    notify_no_corpse_skins="Ceset skin'i seçilmedi.",notify_missing_corpse="%s eksik. Durduruluyor.",notify_no_req="Requiem Ok yok. Durduruluyor.",notify_no_green="Green Baby yok. Durduruluyor.",
    notify_select_skin="En az bir skin seç.",notify_remove_stand="Stand/Skin takılı (%s). Önce kaldır!",notify_in_combat="Savaştasın.",notify_target_skin="Hedef skin alındı: %s",
    status_wait_combat="Bekleniyor — savaşta",status_wait_stun="Bekleniyor — sersemletilmiş / hareket",status_storing="StandStorage slotuna kaydediliyor...",status_removing="Stand kaldırılıyor...",
    status_rolling="%s için %s kullanılıyor...",status_using="%s kullanılıyor...",status_using_for="%s için %s kullanılıyor...",status_pity_low="Pity çok düşük (%.1f%% / %.1f%%) — Ok kullanılıyor...",
    status_building_pity="Pity biriktiriliyor: %.1f%% / %.1f%% (sadece Ok)",status_phase1_ge="Aşama 1/2 — Gold Experience için Ok...",status_phase2_req="Aşama 2/2 — Gold Experience'a Requiem Ok...",
    status_phase1_ws="Aşama 1/2 — Whitesnake için Ok...",status_phase2_gb="Aşama 2/2 — Green Baby Whitesnake ile birleştiriliyor...",status_remove_first="Durduruldu — önce Stand/Skin'i kaldır.",
    status_starting="Başlatılıyor — yöntem: %s",status_done="Tamamlandı — skin: %s",status_stopped="Durduruldu.",
}

getgenv().TEXT.ja = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="morik_yt 制作",
    tab_home="ホーム",tab_teleports="テレポート",tab_farm="ファーム",tab_skin="スキンファーム",tab_sell="自動売却",tab_mob="モブファーム",tab_outfit="衣装",tab_sbr="SBR",
    sec_language="言語",sec_info="情報",sec_movement="移動",sec_misc="その他",sec_app="アプリ",sec_chest="宝箱ファーム",sec_meteorite="隕石ファーム",
    sec_skin_sel="スキン選択",sec_farm_settings="ファーム設定",sec_farm_control="ファーム制御",sec_auto_buy="自動購入",
    sec_target="ターゲット選択",sec_move_settings="移動設定",sec_attack="攻撃設定",sec_farm="ファーム",
    sec_player_outfit="プレイヤーと衣装",sec_pieces="パーツ選択",sec_actions="アクション",
    lang_label="インターフェース言語",lang_changed="言語を保存しました。スクリプトを再実行して適用してください。",
    welcome_title="ようこそ",welcome_text="Roblox is Unbreakable へようこそ — morik_yt 制作のスクリプトです。問題がある場合はDiscordに参加してください。わずか$1でプレミアム版の追加機能が使えます。",
    join_discord="Discordに参加",stand_up="立ち上がる",speed_value="速度",speed_hack="スピードハック",jump_value="ジャンプ力",jump_hack="ジャンプハック",
    heal="回復 ($50)",auto_stand="スタンド自動召喚",show_roles="プレイヤー上にロール表示",staff_alert="スタッフ警告",destroy_gui="GUIを閉じる",staff_online="スタッフがオンライン",
    players="プレイヤー",npc_friendly="友好NPC",npc_hostile="敵対NPC",search_all="検索（プレイヤー / NPC）",search_ph="名前を入力...",
    teleport="テレポート",player_not_found="プレイヤーが見つからないかキャラクターがありません。",dim_tears="次元の亀裂",chests="宝箱",
    ground_items="地面のアイテム",chest_types="宝箱の種類",chest_wait="宝箱待機 (秒)",chest_farm="宝箱ファーム",
    meteorite_wait="隕石待機 (秒)",meteorite_farm="隕石ファーム",
    skin_info_title="情報",skin_info_text="Arrow、Pure Arrow、Requiem（GEからGER）、聖人の遺体パーツ、Green Baby（WSからC-Moon）に対応。自動メソッド選択。StandStorage対応。",
    skin_selected="選択済みスキン",skin_status="ファーム状態",skin_pity="スキンPity",none="なし",idle="待機中",pity_ready="（準備完了）",pity_building="（蓄積中）",
    pity_threshold_label=" | しきい値: %s%%",select_skins="スキンを選択",farm_method="ファームメソッド",search_skin="スキンを検索",search_skin_ph="スキン名",
    select_all_skins="全て選択",clear_skins="選択をクリア",use_storage="StandStorageスロットを使用",use_pity="スキンPityしきい値を使用",pity_threshold="Pityしきい値 (%%)",
    skin_auto_farm="スキン自動ファーム",auto_buy_arrows="矢を自動購入 ($15k)",auto_buy_req="Requiem矢を自動購入 ($200k)",
    method_auto="自動",method_arrow="矢",method_pure="純粋な矢",method_requiem="Requiem（GEからGER）",method_corpse="遺体パーツ",method_green="Green Baby（WSからC-Moon）",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="情報",sell_info_text="選択したアイテムを自動的に売却します。上限: 250,000。",
    sell_selected="選択済みアイテム",select_items="アイテムを選択",search_items="アイテムを検索",search_items_ph="アイテム名",select_all_items="全て選択",clear_items="選択をクリア",auto_sell="自動売却",
    target_players="ターゲット — プレイヤー",target_npcs="ターゲット — NPC（敵対）",search="検索",search_farm_ph="プレイヤーまたはNPC名...",
    fly_speed="飛行速度",height_offset="高さオフセット（最小2）",stop_dist="停止距離",max_range="最大検出範囲",atk_delay="攻撃遅延 (秒)",combo_count="コンボ数",
    npcs_farm="NPCファーム",players_farm="プレイヤーファーム",stop_farm="ファーム停止",farm_stopped="ファームを停止しました。",
    outfit_player="プレイヤー",outfit_set="衣装セット",head_piece="頭部パーツ",upper_piece="上半身パーツ",lower_piece="下半身パーツ",misc_piece="その他パーツ",none_opt="（なし）",
    apply_pieces="選択を適用",wear_full="フルセットを着用",clear_outfit="スクリプト衣装を削除",outfit="衣装",char_not_found="キャラクターが見つかりません。",
    outfit_applied="衣装を適用しました！",select_set_first="先にセットを選択してください。",set_pick_pieces="セット: %s — 下からパーツを選択。",
    set_selected="セット: %s\n頭: %s | 上: %s | 下: %s | その他: %s",full_set_applied="フルセット: %s (%s パーツ)。",cleared_pieces="スクリプトの%sパーツを削除しました。",
    tp_finish="ゴールへテレポート",anti_danger="危険ゾーン回避",inf_stamina="無限スタミナ（遺体パーツ必須）",corpse_esp="遺体パーツESP",auto_stage="自動ステージ + バリアバイパス",
    skin_farm="スキンファーム",notify_auto_mixed="自動: 混合タイプ。ファーム中: %s",notify_not_enough="%sが不足しています。停止します。",notify_got_skin="取得: %s",notify_got_skin_stand="取得: %s (%s)",
    notify_no_corpse_skins="遺体スキンが選択されていません。",notify_missing_corpse="%sがありません。停止します。",notify_no_req="Requiem矢がありません。停止します。",notify_no_green="Green Babyがありません。停止します。",
    notify_select_skin="少なくとも1つのスキンを選択してください。",notify_remove_stand="スタンド/スキンが装備されています (%s)。先に外してください！",notify_in_combat="戦闘中です。",notify_target_skin="目標スキンを取得しました: %s",
    status_wait_combat="待機中 — 戦闘中",status_wait_stun="待機中 — スタン / 行動中",status_storing="StandStorageスロットに保存中...",status_removing="スタンドを外しています...",
    status_rolling="%s で %s をロール中...",status_using="%s を使用中...",status_using_for="%s のために %s を使用中...",status_pity_low="Pityが低すぎます (%.1f%% / %.1f%%) — 矢を使用中...",
    status_building_pity="Pityを蓄積中: %.1f%% / %.1f%% (矢のみ)",status_phase1_ge="フェーズ1/2 — Gold Experience用に矢を使用...",status_phase2_req="フェーズ2/2 — Gold ExperienceにRequiem矢を使用...",
    status_phase1_ws="フェーズ1/2 — Whitesnake用に矢を使用...",status_phase2_gb="フェーズ2/2 — Green BabyをWhitesnakeに合成...",status_remove_first="停止 — まずスタンド/スキンを外してください。",
    status_starting="開始 — メソッド: %s",status_done="完了 — スキン: %s",status_stopped="停止しました。",
}

getgenv().TEXT.ko = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="morik_yt 제작",
    tab_home="홈",tab_teleports="텔레포트",tab_farm="파밍",tab_skin="스킨 파밍",tab_sell="자동 판매",tab_mob="몹 파밍",tab_outfit="의상",tab_sbr="SBR",
    sec_language="언어",sec_info="정보",sec_movement="이동",sec_misc="기타",sec_app="앱",sec_chest="상자 파밍",sec_meteorite="운석 파밍",
    sec_skin_sel="스킨 선택",sec_farm_settings="파밍 설정",sec_farm_control="파밍 제어",sec_auto_buy="자동 구매",
    sec_target="대상 선택",sec_move_settings="이동 설정",sec_attack="공격 설정",sec_farm="파밍",
    sec_player_outfit="플레이어 & 의상",sec_pieces="부품 선택",sec_actions="행동",
    lang_label="인터페이스 언어",lang_changed="언어가 저장되었습니다. 적용하려면 스크립트를 다시 실행하세요.",
    welcome_title="환영합니다",welcome_text="Roblox is Unbreakable에 오신 것을 환영합니다 — morik_yt가 만든 스크립트입니다. 문제가 있으면 Discord에 참가하세요. 단 $1로 프리미엄 버전을 이용하세요.",
    join_discord="Discord 참가",stand_up="일어서기",speed_value="속도 값",speed_hack="속도 핵",jump_value="점프 값",jump_hack="점프 핵",
    heal="치유 ($50)",auto_stand="자동 스탠드 소환",show_roles="플레이어 위에 역할 표시",staff_alert="스태프 경고",destroy_gui="GUI 닫기",staff_online="스태프 온라인",
    players="플레이어",npc_friendly="우호적 NPC",npc_hostile="적대적 NPC",search_all="검색 (플레이어 / NPC)",search_ph="이름 입력...",
    teleport="텔레포트",player_not_found="플레이어를 찾을 수 없거나 캐릭터가 없습니다.",dim_tears="차원 균열",chests="상자",
    ground_items="바닥 아이템",chest_types="상자 종류",chest_wait="상자 대기 (초)",chest_farm="상자 파밍",
    meteorite_wait="운석 대기 (초)",meteorite_farm="운석 파밍",
    skin_info_title="정보",skin_info_text="Arrow, Pure Arrow, Requiem(GE→GER), 성자의 시신 부위, Green Baby(WS→C-Moon) 지원. 자동 방법 선택. StandStorage 포함.",
    skin_selected="선택된 스킨",skin_status="파밍 상태",skin_pity="스킨 Pity",none="없음",idle="대기 중",pity_ready=" (준비됨)",pity_building=" (쌓는 중)",
    pity_threshold_label=" | 임계값: %s%%",select_skins="스킨 선택",farm_method="파밍 방법",search_skin="스킨 검색",search_skin_ph="스킨 이름",
    select_all_skins="모두 선택",clear_skins="선택 초기화",use_storage="StandStorage 슬롯 사용",use_pity="스킨 Pity 임계값 사용",pity_threshold="Pity 임계값 (%%)",
    skin_auto_farm="스킨 자동 파밍",auto_buy_arrows="화살 자동 구매 ($15k)",auto_buy_req="레퀴엠 화살 자동 구매 ($200k)",
    method_auto="자동",method_arrow="화살",method_pure="순수 화살",method_requiem="레퀴엠 (GE→GER)",method_corpse="시신 부위",method_green="Green Baby (WS→C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="정보",sell_info_text="선택한 아이템이 자동으로 판매됩니다. 최대 한도: 250,000.",
    sell_selected="선택된 아이템",select_items="아이템 선택",search_items="아이템 검색",search_items_ph="아이템 이름",select_all_items="모두 선택",clear_items="선택 초기화",auto_sell="자동 판매",
    target_players="대상 — 플레이어",target_npcs="대상 — NPC (적대적)",search="검색",search_farm_ph="플레이어 또는 NPC 이름...",
    fly_speed="비행 속도",height_offset="높이 오프셋 (최소 2)",stop_dist="정지 거리",max_range="최대 감지 범위",atk_delay="공격 딜레이 (초)",combo_count="콤보 수",
    npcs_farm="NPC 파밍",players_farm="플레이어 파밍",stop_farm="파밍 정지",farm_stopped="파밍이 정지되었습니다.",
    outfit_player="플레이어",outfit_set="의상 세트",head_piece="머리 부품",upper_piece="상체 부품",lower_piece="하체 부품",misc_piece="기타 부품",none_opt="(없음)",
    apply_pieces="선택 적용",wear_full="풀 세트 착용",clear_outfit="스크립트 의상 제거",outfit="의상",char_not_found="캐릭터를 찾을 수 없습니다.",
    outfit_applied="의상이 적용되었습니다!",select_set_first="먼저 세트를 선택하세요.",set_pick_pieces="세트: %s — 아래에서 부품을 선택하세요.",
    set_selected="세트: %s\n머리: %s | 상체: %s | 하체: %s | 기타: %s",full_set_applied="풀 세트: %s (%s 부품).",cleared_pieces="스크립트 부품 %s개 제거됨.",
    tp_finish="결승선으로 텔레포트",anti_danger="위험 구역 방지",inf_stamina="무한 체력 (시신 부위 필요)",corpse_esp="시신 부위 ESP",auto_stage="자동 스테이지 + 장벽 우회",
    skin_farm="스킨 파밍",notify_auto_mixed="자동: 혼합 유형. 파밍 중: %s",notify_not_enough="%s가 부족합니다. 중단합니다.",notify_got_skin="획득: %s",notify_got_skin_stand="획득: %s (%s)",
    notify_no_corpse_skins="시신 스킨이 선택되지 않았습니다.",notify_missing_corpse="%s가 없습니다. 중단합니다.",notify_no_req="레퀴엠 화살이 없습니다. 중단합니다.",notify_no_green="Green Baby가 없습니다. 중단합니다.",
    notify_select_skin="스킨을 하나 이상 선택하세요.",notify_remove_stand="스탠드/스킨이 장착되어 있습니다 (%s). 먼저 제거하세요!",notify_in_combat="전투 중입니다.",notify_target_skin="목표 스킨 획득: %s",
    status_wait_combat="대기 중 — 전투 중",status_wait_stun="대기 중 — 기절 / 행동 중",status_storing="StandStorage 슬롯에 저장 중...",status_removing="스탠드 제거 중...",
    status_rolling="%s를 위해 %s 사용 중...",status_using="%s 사용 중...",status_using_for="%s를 위해 %s 사용 중...",status_pity_low="Pity가 너무 낮습니다 (%.1f%% / %.1f%%) — 화살 사용 중...",
    status_building_pity="Pity 쌓는 중: %.1f%% / %.1f%% (화살만)",status_phase1_ge="페이즈 1/2 — Gold Experience를 위한 화살...",status_phase2_req="페이즈 2/2 — Gold Experience에 레퀴엠 화살...",
    status_phase1_ws="페이즈 1/2 — Whitesnake를 위한 화살...",status_phase2_gb="페이즈 2/2 — Green Baby를 Whitesnake에 합성...",status_remove_first="중단됨 — 먼저 스탠드/스킨을 제거하세요.",
    status_starting="시작 중 — 방법: %s",status_done="완료 — 스킨: %s",status_stopped="중단됨.",
}

getgenv().TEXT.zh = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="由 morik_yt 制作",
    tab_home="主页",tab_teleports="传送",tab_farm="刷怪",tab_skin="皮肤农场",tab_sell="自动出售",tab_mob="怪物农场",tab_outfit="服装",tab_sbr="SBR",
    sec_language="语言",sec_info="信息",sec_movement="移动",sec_misc="杂项",sec_app="应用",sec_chest="箱子农场",sec_meteorite="陨石农场",
    sec_skin_sel="皮肤选择",sec_farm_settings="农场设置",sec_farm_control="农场控制",sec_auto_buy="自动购买",
    sec_target="目标选择",sec_move_settings="移动设置",sec_attack="攻击设置",sec_farm="农场",
    sec_player_outfit="玩家与服装",sec_pieces="部件选择",sec_actions="操作",
    lang_label="界面语言",lang_changed="语言已保存。重新执行脚本以应用。",
    welcome_title="欢迎",welcome_text="欢迎使用 Roblox is Unbreakable —— morik_yt 制作的脚本。遇到问题请加入 Discord。仅需 $1 即可解锁高级版额外功能。",
    join_discord="加入 Discord",stand_up="站起来",speed_value="速度值",speed_hack="速度外挂",jump_value="跳跃值",jump_hack="跳跃外挂",
    heal="治疗 ($50)",auto_stand="自动召唤替身",show_roles="在玩家上方显示身份",staff_alert="管理员警报",destroy_gui="关闭界面",staff_online="管理员在线",
    players="玩家",npc_friendly="友好NPC",npc_hostile="敌对NPC",search_all="搜索（玩家 / NPC）",search_ph="输入名称...",
    teleport="传送",player_not_found="未找到玩家或无角色。",dim_tears="次元裂缝",chests="箱子",
    ground_items="地面物品",chest_types="箱子类型",chest_wait="箱子等待 (秒)",chest_farm="箱子农场",
    meteorite_wait="陨石等待 (秒)",meteorite_farm="陨石农场",
    skin_info_title="信息",skin_info_text="支持 Arrow、Pure Arrow、Requiem（GE→GER）、圣人遗骸部件和 Green Baby（WS→C-Moon）。自动方法选择。包含 StandStorage。",
    skin_selected="已选皮肤",skin_status="农场状态",skin_pity="皮肤 Pity",none="无",idle="空闲",pity_ready="（就绪）",pity_building="（积累中）",
    pity_threshold_label=" | 阈值: %s%%",select_skins="选择皮肤",farm_method="农场方式",search_skin="搜索皮肤",search_skin_ph="皮肤名称",
    select_all_skins="全选",clear_skins="清除选择",use_storage="使用 StandStorage 槽位",use_pity="使用皮肤 Pity 阈值",pity_threshold="Pity 阈值 (%%)",
    skin_auto_farm="自动皮肤农场",auto_buy_arrows="自动购买箭矢 ($15k)",auto_buy_req="自动购买 Requiem 箭矢 ($200k)",
    method_auto="自动",method_arrow="箭矢",method_pure="纯净箭矢",method_requiem="Requiem（GE→GER）",method_corpse="遗骸部件",method_green="Green Baby（WS→C-Moon）",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="信息",sell_info_text="所选物品将自动出售。最高上限：250,000。",
    sell_selected="已选物品",select_items="选择物品",search_items="搜索物品",search_items_ph="物品名称",select_all_items="全选",clear_items="清除选择",auto_sell="自动出售",
    target_players="目标 — 玩家",target_npcs="目标 — NPC（敌对）",search="搜索",search_farm_ph="玩家或NPC名称...",
    fly_speed="飞行速度",height_offset="高度偏移（最小2）",stop_dist="停止距离",max_range="最大探测范围",atk_delay="攻击延迟 (秒)",combo_count="连击数",
    npcs_farm="NPC农场",players_farm="玩家农场",stop_farm="停止农场",farm_stopped="农场已停止。",
    outfit_player="玩家",outfit_set="服装套装",head_piece="头部部件",upper_piece="上身部件",lower_piece="下身部件",misc_piece="其他部件",none_opt="（无）",
    apply_pieces="应用所选",wear_full="穿戴完整套装",clear_outfit="移除脚本服装",outfit="服装",char_not_found="未找到角色。",
    outfit_applied="服装已应用！",select_set_first="请先选择套装。",set_pick_pieces="套装: %s — 在下方选择部件。",
    set_selected="套装: %s\n头部: %s | 上身: %s | 下身: %s | 其他: %s",full_set_applied="完整套装: %s (%s 件部件)。",cleared_pieces="已移除 %s 个脚本部件。",
    tp_finish="传送到终点线",anti_danger="防危险区域",inf_stamina="无限耐力（需要遗骸部件）",corpse_esp="遗骸部件ESP",auto_stage="自动阶段 + 屏障绕过",
    skin_farm="皮肤农场",notify_auto_mixed="自动: 混合类型。正在农场: %s",notify_not_enough="%s 不足。停止。",notify_got_skin="获得: %s",notify_got_skin_stand="获得: %s (%s)",
    notify_no_corpse_skins="未选择遗骸皮肤。",notify_missing_corpse="缺少 %s。停止。",notify_no_req="没有 Requiem 箭矢。停止。",notify_no_green="没有 Green Baby。停止。",
    notify_select_skin="至少选择一个皮肤。",notify_remove_stand="替身/皮肤已装备 (%s)。请先移除！",notify_in_combat="你正在战斗中。",notify_target_skin="目标皮肤已获得: %s",
    status_wait_combat="等待中 — 战斗中",status_wait_stun="等待中 — 眩晕/动作中",status_storing="正在存入 StandStorage 槽位...",status_removing="正在移除替身...",
    status_rolling="正在为 %s 使用 %s...",status_using="正在使用 %s...",status_using_for="正在为 %s 使用 %s...",status_pity_low="Pity 过低 (%.1f%% / %.1f%%) — 正在使用箭矢...",
    status_building_pity="正在积累 Pity: %.1f%% / %.1f%%（仅箭矢）",status_phase1_ge="阶段 1/2 — 使用箭矢获取 Gold Experience...",status_phase2_req="阶段 2/2 — 对 Gold Experience 使用 Requiem 箭矢...",
    status_phase1_ws="阶段 1/2 — 使用箭矢获取 Whitesnake...",status_phase2_gb="阶段 2/2 — 将 Green Baby 与 Whitesnake 合并...",status_remove_first="已停止 — 请先移除替身/皮肤。",
    status_starting="启动中 — 方式: %s",status_done="完成 — 皮肤: %s",status_stopped="已停止。",
}

getgenv().TEXT.ar = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="بواسطة morik_yt",
    tab_home="الرئيسية",tab_teleports="نقل فوري",tab_farm="زراعة",tab_skin="زراعة السكن",tab_sell="بيع تلقائي",tab_mob="زراعة المخلوقات",tab_outfit="ملابس",tab_sbr="SBR",
    sec_language="اللغة",sec_info="معلومات",sec_movement="الحركة",sec_misc="متنوع",sec_app="التطبيق",sec_chest="زراعة الصناديق",sec_meteorite="زراعة النيازك",
    sec_skin_sel="اختيار السكن",sec_farm_settings="إعدادات الزراعة",sec_farm_control="التحكم في الزراعة",sec_auto_buy="شراء تلقائي",
    sec_target="اختيار الهدف",sec_move_settings="إعدادات الحركة",sec_attack="إعدادات الهجوم",sec_farm="زراعة",
    sec_player_outfit="اللاعب والملابس",sec_pieces="اختيار القطع",sec_actions="الإجراءات",
    lang_label="لغة الواجهة",lang_changed="تم حفظ اللغة. أعد تشغيل السكريبت للتطبيق.",
    welcome_title="مرحباً",welcome_text="مرحباً بك في Roblox is Unbreakable — سكريبت من صنع morik_yt. إذا واجهت مشاكل انضم إلى ديسكورد. النسخة المميزة بـ $1 فقط.",
    join_discord="انضم للديسكورد",stand_up="قف",speed_value="قيمة السرعة",speed_hack="هاك السرعة",jump_value="قيمة القفز",jump_hack="هاك القفز",
    heal="علاج ($50)",auto_stand="استدعاء ستاند تلقائي",show_roles="عرض الأدوار فوق اللاعبين",staff_alert="تنبيه طاقم العمل",destroy_gui="إغلاق الواجهة",staff_online="طاقم العمل متصل",
    players="اللاعبون",npc_friendly="NPC ودي",npc_hostile="NPC عدائي",search_all="بحث (لاعبون / NPC)",search_ph="أدخل اسماً...",
    teleport="نقل فوري",player_not_found="اللاعب غير موجود أو لا يملك شخصية.",dim_tears="تمزقات بُعدية",chests="صناديق",
    ground_items="عناصر على الأرض",chest_types="أنواع الصناديق",chest_wait="انتظار الصندوق (ث)",chest_farm="زراعة الصناديق",
    meteorite_wait="انتظار النيزك (ث)",meteorite_farm="زراعة النيازك",
    skin_info_title="معلومات",skin_info_text="يدعم Arrow وPure Arrow وRequiem وأجزاء جسد القديس وGreen Baby. اختيار تلقائي للطريقة. يشمل StandStorage.",
    skin_selected="السكنات المختارة",skin_status="حالة الزراعة",skin_pity="Skin Pity",none="لا شيء",idle="خامل",pity_ready=" (جاهز)",pity_building=" (يتراكم)",
    pity_threshold_label=" | الحد: %s%%",select_skins="اختر سكنات",farm_method="طريقة الزراعة",search_skin="ابحث عن سكن",search_skin_ph="اسم السكن",
    select_all_skins="اختر الكل",clear_skins="مسح الاختيار",use_storage="استخدام فتحات StandStorage",use_pity="استخدام حد Skin Pity",pity_threshold="حد Pity (%%)",
    skin_auto_farm="زراعة سكن تلقائية",auto_buy_arrows="شراء سهام تلقائي ($15k)",auto_buy_req="شراء سهام Requiem تلقائي ($200k)",
    method_auto="تلقائي",method_arrow="سهم",method_pure="سهم نقي",method_requiem="Requiem (GE إلى GER)",method_corpse="أجزاء الجسد",method_green="Green Baby (WS إلى C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="معلومات",sell_info_text="ستُباع العناصر المختارة تلقائياً. الحد الأقصى: 250,000.",
    sell_selected="العناصر المختارة",select_items="اختر عناصر",search_items="ابحث عن عناصر",search_items_ph="اسم العنصر",select_all_items="اختر الكل",clear_items="مسح الاختيار",auto_sell="بيع تلقائي",
    target_players="الهدف — اللاعبون",target_npcs="الهدف — NPC (عدائي)",search="بحث",search_farm_ph="اسم اللاعب أو NPC...",
    fly_speed="سرعة الطيران",height_offset="إزاحة الارتفاع (الحد الأدنى 2)",stop_dist="مسافة التوقف",max_range="أقصى نطاق اكتشاف",atk_delay="تأخير الهجوم (ث)",combo_count="عدد الكومبو",
    npcs_farm="زراعة NPCs",players_farm="زراعة اللاعبين",stop_farm="إيقاف الزراعة",farm_stopped="توقفت الزراعة.",
    outfit_player="لاعب",outfit_set="مجموعة ملابس",head_piece="قطعة الرأس",upper_piece="قطعة علوية",lower_piece="قطعة سفلية",misc_piece="قطعة متنوعة",none_opt="(لا شيء)",
    apply_pieces="تطبيق المختار",wear_full="ارتداء المجموعة كاملة",clear_outfit="إزالة ملابس السكريبت",outfit="ملابس",char_not_found="الشخصية غير موجودة.",
    outfit_applied="تم تطبيق الملابس!",select_set_first="اختر مجموعة أولاً.",set_pick_pieces="المجموعة: %s — اختر القطع أدناه.",
    set_selected="المجموعة: %s\nرأس: %s | علوي: %s | سفلي: %s | متنوع: %s",full_set_applied="المجموعة الكاملة: %s (%s قطعة).",cleared_pieces="تمت إزالة %s قطعة(قطع) من السكريبت.",
    tp_finish="نقل فوري إلى خط النهاية",anti_danger="منطقة مانعة للخطر",inf_stamina="قدرة تحمل لا نهائية (يتطلب جزء جسد)",corpse_esp="ESP لأجزاء الجسد",auto_stage="مرحلة تلقائية + تجاوز الحاجز",
    skin_farm="زراعة سكن",notify_auto_mixed="تلقائي: أنواع مختلطة. الزراعة: %s",notify_not_enough="لا يوجد %s كافٍ. إيقاف.",notify_got_skin="تم الحصول على: %s",notify_got_skin_stand="تم الحصول على: %s (%s)",
    notify_no_corpse_skins="لم يتم اختيار سكنات الجسد.",notify_missing_corpse="%s مفقود. إيقاف.",notify_no_req="لا توجد سهام Requiem. إيقاف.",notify_no_green="لا يوجد Green Baby. إيقاف.",
    notify_select_skin="اختر سكناً واحداً على الأقل.",notify_remove_stand="الستاند/السكن مجهز (%s). أزله أولاً!",notify_in_combat="أنت في قتال.",notify_target_skin="تم الحصول على السكن المستهدف: %s",
    status_wait_combat="في انتظار — في قتال",status_wait_stun="في انتظار — مذهول / يؤدي حركة",status_storing="جاري الحفظ في فتحة StandStorage...",status_removing="جاري إزالة الستاند...",
    status_rolling="جاري استخدام %s لـ %s...",status_using="جاري استخدام %s...",status_using_for="جاري استخدام %s لـ %s...",status_pity_low="Pity منخفض جداً (%.1f%% / %.1f%%) — جاري استخدام السهم...",
    status_building_pity="تراكم Pity: %.1f%% / %.1f%% (سهم فقط)",status_phase1_ge="المرحلة 1/2 — سهم لـ Gold Experience...",status_phase2_req="المرحلة 2/2 — سهم Requiem على Gold Experience...",
    status_phase1_ws="المرحلة 1/2 — سهم لـ Whitesnake...",status_phase2_gb="المرحلة 2/2 — دمج Green Baby مع Whitesnake...",status_remove_first="إيقاف — أزل الستاند/السكن أولاً.",
    status_starting="جاري البدء — الطريقة: %s",status_done="اكتمل — السكن: %s",status_stopped="متوقف.",
}

getgenv().TEXT.pl = {
    window_name="Roblox is Unbreakable | @morik_yt v%s",loading_title="Roblox is Unbreakable",loading_subtitle="przez morik_yt",
    tab_home="Główna",tab_teleports="Teleporty",tab_farm="Farmienie",tab_skin="Farm skinów",tab_sell="Auto-sprzedaż",tab_mob="Farm mobów",tab_outfit="Strój",tab_sbr="SBR",
    sec_language="Język",sec_info="Informacje",sec_movement="Ruch",sec_misc="Różne",sec_app="Aplikacja",sec_chest="Farm skrzyń",sec_meteorite="Farm meteorytów",
    sec_skin_sel="Wybór skinów",sec_farm_settings="Ustawienia farmy",sec_farm_control="Sterowanie farmą",sec_auto_buy="Auto-zakup",
    sec_target="Wybór celu",sec_move_settings="Ustawienia ruchu",sec_attack="Ustawienia ataku",sec_farm="Farmienie",
    sec_player_outfit="Gracz i strój",sec_pieces="Wybór elementów",sec_actions="Akcje",
    lang_label="Język interfejsu",lang_changed="Język zapisany. Uruchom skrypt ponownie, aby zastosować.",
    welcome_title="Witaj",welcome_text="Witaj w Roblox is Unbreakable — skrypcie stworzonym przez morik_yt. Jeśli napotkasz problemy, dołącz do Discorda. Wersja Premium za jedyne $1.",
    join_discord="Dołącz do Discorda",stand_up="Wstań",speed_value="Wartość prędkości",speed_hack="Speed Hack",jump_value="Wartość skoku",jump_hack="Jump Hack",
    heal="Leczenie ($50)",auto_stand="Auto-przywołanie Standa",show_roles="Pokaż role nad graczami",staff_alert="Alert staffu",destroy_gui="Zamknij GUI",staff_online="Staff online",
    players="Gracze",npc_friendly="NPC przyjazne",npc_hostile="NPC wrogie",search_all="Szukaj (Gracze / NPC)",search_ph="Wpisz nazwę...",
    teleport="Teleport",player_not_found="Gracz nie znaleziony lub brak postaci.",dim_tears="Rozdarcia wymiarowe",chests="Skrzynie",
    ground_items="Przedmioty na ziemi",chest_types="Typy skrzyń",chest_wait="Oczekiwanie skrzyni (s)",chest_farm="Farm skrzyń",
    meteorite_wait="Oczekiwanie meteorytu (s)",meteorite_farm="Farm meteorytów",
    skin_info_title="Info",skin_info_text="Obsługuje Arrow, Pure Arrow, Requiem (GE do GER), części ciała świętego i Green Baby (WS do C-Moon). Automatyczny dobór metody. Obsługa StandStorage.",
    skin_selected="Wybrane skiny",skin_status="Status farmy",skin_pity="Skin Pity",none="Brak",idle="Bezczynny",pity_ready=" (gotowy)",pity_building=" (kumulowanie)",
    pity_threshold_label=" | Próg: %s%%",select_skins="Wybierz skiny",farm_method="Metoda farmienia",search_skin="Szukaj skina",search_skin_ph="Nazwa skina",
    select_all_skins="Zaznacz wszystko",clear_skins="Wyczyść wybór",use_storage="Używaj slotów StandStorage",use_pity="Używaj progu Skin Pity",pity_threshold="Próg Pity (%%)",
    skin_auto_farm="Auto-farm skinów",auto_buy_arrows="Auto-zakup strzał ($15k)",auto_buy_req="Auto-zakup strzał Requiem ($200k)",
    method_auto="Auto",method_arrow="Strzała",method_pure="Czysta strzała",method_requiem="Requiem (GE do GER)",method_corpse="Części ciała",method_green="Green Baby (WS do C-Moon)",
    method_key_auto="Auto",method_key_arrow="Arrow",method_key_pure="Pure Arrow",method_key_requiem="Requiem",method_key_corpse="Corpse",method_key_green="GreenBaby",
    sell_info_title="Informacje",sell_info_text="Wybrane przedmioty zostaną automatycznie sprzedane. Limit: 250 000.",
    sell_selected="Wybrane przedmioty",select_items="Wybierz przedmioty",search_items="Szukaj przedmiotów",search_items_ph="Nazwa przedmiotu",select_all_items="Zaznacz wszystko",clear_items="Wyczyść wybór",auto_sell="Auto-sprzedaż",
    target_players="Cel — Gracze",target_npcs="Cel — NPC (Wrogie)",search="Szukaj",search_farm_ph="Nazwa gracza lub NPC...",
    fly_speed="Prędkość lotu",height_offset="Przesunięcie wysokości (min 2)",stop_dist="Dystans zatrzymania",max_range="Maks. zasięg wykrywania",atk_delay="Opóźnienie ataku (s)",combo_count="Liczba ciosów combo",
    npcs_farm="Farm NPC",players_farm="Farm graczy",stop_farm="Zatrzymaj farmę",farm_stopped="Farma zatrzymana.",
    outfit_player="Gracz",outfit_set="Zestaw stroju",head_piece="Element głowy",upper_piece="Element górny",lower_piece="Element dolny",misc_piece="Element różny",none_opt="(brak)",
    apply_pieces="Zastosuj wybrane",wear_full="Załóż pełny zestaw",clear_outfit="Usuń strój skryptu",outfit="Strój",char_not_found="Nie znaleziono postaci.",
    outfit_applied="Strój zastosowany!",select_set_first="Najpierw wybierz zestaw.",set_pick_pieces="Zestaw: %s — wybierz elementy poniżej.",
    set_selected="Zestaw: %s\nGłowa: %s | Góra: %s | Dół: %s | Różne: %s",full_set_applied="Pełny zestaw: %s (%s elementów).",cleared_pieces="Usunięto %s element(ów) skryptu.",
    tp_finish="Teleport do mety",anti_danger="Anty-strefa niebezpieczna",inf_stamina="Nieskończona wytrzymałość (wymaga części ciała)",corpse_esp="ESP części ciała",auto_stage="Auto-etap + pominięcie bariery",
    skin_farm="Farm skinów",notify_auto_mixed="Auto: typy mieszane. Farmię: %s",notify_not_enough="Za mało %s. Zatrzymuję.",notify_got_skin="Zdobyto: %s",notify_got_skin_stand="Zdobyto: %s (%s)",
    notify_no_corpse_skins="Nie wybrano skinów ze zwłok.",notify_missing_corpse="Brak %s. Zatrzymuję.",notify_no_req="Brak strzał Requiem. Zatrzymuję.",notify_no_green="Brak Green Baby. Zatrzymuję.",
    notify_select_skin="Wybierz co najmniej jeden skin.",notify_remove_stand="Masz założony stand/skin (%s). Najpierw go zdejmij!",notify_in_combat="Jesteś w walce.",notify_target_skin="Docelowy skin zdobyty: %s",
    status_wait_combat="Oczekiwanie — w walce",status_wait_stun="Oczekiwanie — ogłuszony / wykonuje ruch",status_storing="Zapisywanie do slotu StandStorage...",status_removing="Zdejmowanie standa...",
    status_rolling="Rzucam %s dla %s...",status_using="Używam %s...",status_using_for="Używam %s dla %s...",status_pity_low="Pity zbyt niskie (%.1f%% / %.1f%%) — rzucam strzałą...",
    status_building_pity="Kumuluję pity: %.1f%% / %.1f%% (tylko strzały)",status_phase1_ge="Faza 1/2 — strzała dla Gold Experience...",status_phase2_req="Faza 2/2 — strzała Requiem na Gold Experience...",
    status_phase1_ws="Faza 1/2 — strzała dla Whitesnake...",status_phase2_gb="Faza 2/2 — łączę Green Baby z Whitesnake...",status_remove_first="Zatrzymano — najpierw zdejmij stand/skin.",
    status_starting="Rozpoczynanie — metoda: %s",status_done="Gotowe — skin: %s",status_stopped="Zatrzymano.",
}

loadstring(game:HttpGet("https://raw.githubusercontent.com/MorikTV/Roblox-is-Unbreakable/refs/heads/main/paid.lua", true))()

--getgenv().syn = syn

-- end
